version: 2.1

jobs:
  build-test:
    docker:
      - image: circleci/node:14  # Meilleur support pour React

    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            - v3-dependencies-

      - run:
          name: Install dependencies (include devDeps)
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: npm test -- --watchAll=false

      - run:
          name: Build project
          command: npm run build

      - run:
          name: Run npm audit (critical only)
          command: npm audit --audit-level=critical

workflows:
  node-tests:
    jobs:
      - build-test