version: 2.1

jobs:
  build-test:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "package.json" }}
            - v4-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v4-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: npx react-scripts test --watchAll=false

      - run:
          name: Build project
          command: npx react-scripts build

      - run:
          name: Run npm audit (critical only)
          command: npm audit --audit-level=critical

workflows:
  node-tests:
    jobs:
      - build-test